name: Content has an Error
description: I found an error in the content
title: "[CONTENT_CORRECTION]: (Song Title here)"
labels: ["CONTENT_CORRECTION", "triage"]
assignees:
  - thehandsomezebra
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this form!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: textarea
    id: what-song
    attributes:
      label: What song?
      description: A link to the orishamusic.info specific song page.  
      placeholder: Add a link, song title & orisha this is for.
      value: |
        Song link: 
        Song title: 
        Orisha: 
    validations:
      required: true
      
  - type: textarea
    id: remove-what
    attributes:
      label: What is the error?
      description: Please let me know the error you found. (ex. wrong lyrics, wrong translation, broken song link, etc.)
      placeholder: Describe what the error.
    validations:
      required: true
