name: I found audio for a song
description: I would like to add audio content to the site.
title: "[ADD_AUDIO]: (Song Title here)"
labels: ["ADD_AUDIO", "triage"]
assignees:
  - thehandsomezebra
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this form!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: textarea
    id: what-song
    attributes:
      label: What song?
      description: A link to the orishamusic.info specific song page.  
      placeholder: Add a link, song title & orisha this is for.
      value: |
        Song link: 
        Song title: 
        Orisha: 
    validations:
      required: true
      
  - type: textarea
    id: where-from
    attributes:
      label: Where's the audio?
      description: A link to the audio via youtube, spotify, etc would be appreciated.  Other forms like describing the artist, album and track on a CD will also work.
      placeholder: Add a link to the source of the audio
      value: |
        Audio link: 
        Artist: 
        Album: (if known)
        Track: (if known)
    validations:
      required: true

  - type: textarea
    id: what-audio
    attributes:
      label: Where in the audio?
      description: A clear and concise description of where to locate the audio for this song.
      placeholder: In the youtube video, you can hear the call and response between timestamps 0:58-1:37
      value:  |
        Audio starts: 
        Audio ends:  
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context you can provide, if applicable.
      placeholder: Anything else?
    validations:
      required: false
